### ISSUE TITLE
Retrieving list of roles without pagination

### ISSUE THREAD

**Issue by zakaria-root** [projet-d-innovation/delib-backend#33]
We need the ability to retrieve a list of all the roles.
It is necessary when we want to add roles to a new user in the Frontend.

**Comment by Elbouchouki** [comment]
You can choose to use the paginated endpoint with a larger item size, or for optimal performance, consider using an asynchronous dropdown. However, implementing a non-paginated endpoint to retrieve a list of all roles won't be practical due to potential performance issues.

**Comment by zakaria-root** [comment]
I believe that the current approach is not optimal, as it retrieves unnecessary information such as the page number and total number of pages for each request.

**Comment by Elbouchouki** [comment]
Do you believe that retrieving two additional variables is more costly than retrieving the whole data?

**Comment by zakaria-root** [comment]
But, In any case, you must retrieve all the data with the maximum number of element

**Comment by Elbouchouki** [comment]
If you choose to use an asynchronous dropdown which is the most optimal way. You won't need to load all the data.
For now, please use the paginated endpoint instead of the non-paginated one. I will inform you when the non-paginated endpoint is available, and at that time, you can switch to it. I will close this issue once the implementation is complete.

**Comment by zakaria-root** [comment]
Ok
